name: Nitya CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        run: |
          git clone https://github.com/infinite-options/Nitya-Backend.git
          cd Nitya-Backend
          ls

      - name: Set Up Python
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-venv build-essential
          python3 --version

      - name: Install Dependencies
        run: |
          cd Nitya-Backend
          pip install --upgrade pip setuptools wheel Cython
          pip3 install -r requirements.txt --no-deps

      - name: Run app to test
        id: test
        run: |
          cd Nitya-Backend
          python3 nitya_api.py &
          sleep 10
          if ! pgrep -f "python3 nitya_api.py"; then
            echo "App failed to start"
            exit 1
          fi

      - name: Deploy to EC2
        if: success()
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER}}
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "${SSH_PRIVATE_KEY}" > ssh_key.pem
          chmod 600 ssh_key.pem
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem $EC2_USER@$EC2_HOST << EOF
            echo "Connected to EC2 instance"
            cd /home/ec2-user/nitya-backend
            source .venv/bin/activate
            cd Nitya-Backend
            echo "Pulling latest code..."
            git pull origin master
            echo "Restarting application..."
            pkill -f "python3 nitya_api.py" || echo "No existing app running"
            echo "Installing dependencies..."
            pip3 install -r requirements.txt --no-deps
            nohup python3 nitya_api.py >> nitya.log 2>&1 &
            echo "Application started"
            exit 0
          EOF
